name: NWChem_CI

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
jobs:
  build:
    if: |
      github.event_name == 'schedule' ||
      (!contains(github.event.head_commit.message, 'ci skip'))
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        experimental: [false]
        mpi_impl:
          - openmpi
          - mpich
        armci_network:
          - MPI-TS
        xcode_version:
          - 11.7
        nwchem_modules:
          - "tinyqmpw python"
          - "qmandpw qmd"
          - "tce"
        fc:
          - gfortran-9
        exclude:
          - os: macos-10.15 
            mpi_impl: mpich
            nwchem_modules: "tinyqmpw python"
          - os: macos-10.15 
            mpi_impl: mpich
            nwchem_modules: "qmandpw qmd"
        include:
          - os: ubuntu-20.04
            experimental: true
            mpi_impl: mpich
            armci_network: mpi-ts
            nwchem_modules: "tinyqmpw python"
            fc: flang
            cc: clang
          - os: ubuntu-20.04
            experimental: true
            mpi_impl: intel
            armci_network: mpi-pr
            nwchem_modules: "tinyqmpw python"
            fc: ifort
          - os: ubuntu-20.04
            experimental: true
            mpi_impl: intel
            armci_network: sockets
            nwchem_modules: "tce"
            fc: ifort
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: mpich
            armci_network: mpi-ts
            nwchem_modules: "tce"
            fc: flang
            cc: clang
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: intel
            armci_network: mpi-pr
            nwchem_modules: "tinyqmpw python"
            fc: ifort
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: intel
            armci_network: sockets
            nwchem_modules: "tce"
            fc: ifort
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: mpich
            armci_network: mpi-pt
            nwchem_modules: "nwdft solvation driver"
            fc: gfortran-10
            use_simint: 1
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: mpich
            armci_network: mpi-pr
            nwchem_modules: "tinyqmpw python"
            fc: gfortran-10
          - os: macos-10.15
            experimental: true 
            mpi_impl: openmpi
            armci_network: mpi-pr
            nwchem_modules: "qmandpw qmd"
            fc: gfortran-10
            xcode_version: 12.3
          - os: macos-10.15
            experimental: true
            mpi_impl: openmpi
            armci_network: mpi-pr
            nwchem_modules: "tce"
            fc: gfortran-10
            xcode_version: 12.3
      fail-fast: false
    env:
        MPI_IMPL: ${{ matrix.mpi_impl }}
        ARMCI_NETWORK: ${{ matrix.armci_network }}
        NWCHEM_MODULES: ${{ matrix.nwchem_modules }}
        USE_SIMINT: ${{ matrix.use_simint }}
        FC: ${{ matrix.fc }}
        COMEX_MAX_NB_OUTSTANDING: 4
        SIMINT_MAXAM: 3
        SIMINT_VECTOR: avx2
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version}}.app/Contents/Developer
    continue-on-error: ${{ matrix.experimental }}
    steps: 
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
          key: ${{ matrix.os }}-${{ matrix.mpi_impl}}-${{ matrix.fc}}-xcode${{ matrix.xcode_version}}-simint${{ matrix.use_simint}}-nwchemcache-v003
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 40
      - name: build environment
        run: |
          pwd
          ls -lart
          ./travis/build_env.sh
      - name: fetch cache
        if: steps.setup-cache.outputs.cache-hit == 'true'
        run: |
          [ -d ~/cache/libext ] && mkdir -p ~/cache/libext/mpich/mpich  && \
          rsync -av ~/cache/libext/* src/libext/.  
          [ -d ~/cache/simint/simint_install/lib ] && \
          mkdir -p src/NWints/simint/libsimint_source/simint_install && \
          rsync -av ~/cache/simint/simint_install/* src/NWints/simint/libsimint_source/simint_install/.   || true
          echo "cache fetched"
      - name: compile
        run: |
          cc -v
          ./travis/compile_nwchem.sh
      - name: Check compilation result
        if: ${{ failure() }}
        run: |
          cat src/tools/build/config.log || true
          cat src/tools/build/comex/config.log || true
      - name: store cache
        run: |
          mkdir -p ~/cache/libext/lib  ~/cache/libext/bin  ~/cache/libext/include ~/cache/libext/mpich || true
          mkdir -p ~/cache/simint/simint_install || true
          [ -d "src/libext/lib" ] && rsync -av src/libext/lib/*  ~/cache/libext/lib/. || true
          [ -d "src/libext/bin" ] && rsync -av src/libext/bin/*  ~/cache/libext/bin/. || true
          [ -d "src/libext/include" ] && rsync -av src/libext/include/*  ~/cache/libext/include/.  || true
          [ -d "src/NWints/simint/libsimint_source/simint_install/lib" ] && rsync -av src/NWints/simint/libsimint_source/simint_install/* ~/cache/simint/simint_install/.  || true
          mkdir -p ~/cache/libext/mpich/mpich || true
          echo "cache stored"
          ls -Rla ~/cache 
      - name: qa_test
        if: ${{ success() }}
        run: |
          ./travis/run_qas.sh
      - name: Check if QA testing has failed
        if: ${{ failure() }}
        run: |
          grep d= QA/testoutputs/dft_he2+.out
          grep @ QA/testoutputs/h2o_opt.out
          tail -30 QA/testoutputs/dft_he2+.out
          tail -490 QA/testoutputs/h2o2-response.out
          tail -30 QA/testoutputs/prop_mep_gcube.out
          diff QA/testoutputs/prop_ch3f.o*nw*
          diff QA/testoutputs/h2o2-response.o*nw*
  



     
